### PR TITLE
chore: bump LWS version to v0.4.0

### PR DESCRIPTION
**Pull request by googs1025**
/kind cleanup
#### What this PR does / why we need it
- bump LWS version to v0.4.0
#### Which issue(s) this PR fixes

Fixes https://github.com/InftyAI/llmaz/issues/161

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by kerthcet** [comment]
FYI: this is already reported in https://github.com/kubernetes-sigs/controller-tools/issues/1017 and fixed.

**Comment by kerthcet** [comment]
But you need to do is just bump the `CONTROLLER_TOOLS_VERSION ?= v0.16.1` as well.

**Comment by googs1025** [comment]
I will handle it tonight.

**Comment by kerthcet** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
